网站展示项目/JobAs/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('app01.urls')),

]





网站展示项目/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    # ex: /accounts/login/
    path('login/', views.custom_login, name="login"),
    # ex: /accounts/logout/
    path('logout/', views.custom_logout, name="logout"),
    # ex: /accounts/register/
    path('register/', views.register, name="register"),
    # ex: /accounts/userprofile/
    path('userprofile/', views.update_userprofile, name="userprofile"),
    
]

网站展示项目/app01/urls.py
from app01 import views
from django.urls import include, path
app_name = "app01"
urlpatterns = [
    path('', views.Index, name='index'),
    path('salary/', views.Salary, name='salary'),
    path('district/', views.District, name='district'),
    path('districtLine/', views.DistrictLine, name='districtLine'),
    path('education/', views.Education, name='education'),
    path('wordCloud/', views.WordCloudT, name='wordCloud'),
    path('demo/PositionNameView/',views.PositionNameView.as_view(), name='PositionNameView'),
    path('demo/SalaryView/',views.SalaryView.as_view(), name='SalaryView'),
    path('demo/EducationView/',views.EducationView.as_view(), name='EducationView'),
    path('demo/WordCloudView/',views.WordCloudView.as_view(), name='WordCloudView'),
    path('demo/DistrictView/',views.DistrictView.as_view(), name='DistrictView'),
    path('demo/DistrictLineView/',views.DistrictLineView.as_view(), name='DistrictLineView'),
    path('my-page/', views.my_page, name='my-page'),
]

网站展示项目/app01/models.py
from django.db import models


class partJobInfo(models.Model):
    city = models.CharField(max_length=255, verbose_name="城市")
    county = models.CharField(verbose_name="分布范围", max_length=255)
    type_j = models.CharField(verbose_name="职位类型", max_length=255)  # 工作类别
    education = models.CharField(max_length=255, verbose_name="学历")
    detail_url = models.CharField(max_length=255, verbose_name="职位URL")
    jobName = models.CharField(max_length=255, verbose_name="职位名称")
    readCount = models.IntegerField(verbose_name="浏览量")
    salary = models.CharField(max_length=255, verbose_name="工资")
    price = models.FloatField( verbose_name='时薪', default='')
    dateTime = models.DateTimeField(verbose_name="发布时间")
    companyName = models.CharField(max_length=255, verbose_name="招聘单位")
    desc = models.TextField(verbose_name="描述信息")

    class Meta:
        verbose_name = "兼职信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.jobName


class City(models.Model):
    name = models.CharField(verbose_name="城市名称", max_length=255)
    JobCount = models.IntegerField(verbose_name="兼职数量")

    class Meta:
        verbose_name = "城市"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

网站展示项目/app01/views.py
import json
from random import randrange
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse
from django.shortcuts import render
from rest_framework.views import APIView

from pyecharts.charts import Bar, Geo, WordCloud, Line
from pyecharts.charts import Pie
from pyecharts import options as opts
from pyecharts.faker import Faker
from app01.models import partJobInfo
from pyecharts.globals import ChartType
import re


# Create your views here.
def response_as_json(data):
    json_str = json.dumps(data)
    response = HttpResponse(
        json_str,
        content_type="application/json",
    )
    response["Access-Control-Allow-Origin"] = "*"
    return response


def json_response(data, code=200, *args, **kwargs):
    data = {
        "code": code,
        "msg": "success",
        "data": data,
    }
    return response_as_json(data)


def json_error(error_string="error", code=500, **kwargs):
    data = {
        "code": code,
        "msg": error_string,
        "data": {}
    }
    data.update(kwargs)
    return response_as_json(data)


JsonResponse = json_response
JsonError = json_error


def pie_position(start=100, end=150) -> Pie():
    ress = partJobInfo.objects.all()
    position_info_dic = {}
    for i in ress:
        if i.type_j in position_info_dic:
            position_info_dic[i.type_j] += 1
        else:
            position_info_dic[i.type_j] = 1
    try:
        position_pie = (

            Pie()
                .add(
                "",

                list(position_info_dic.items())
                ,
                center=["40%", "50%"],
            )
                .set_global_opts(
                title_opts=opts.TitleOpts(title="工作类别饼图"),
                legend_opts=opts.LegendOpts(type_="scroll", pos_left="80%", orient="vertical"),
            )
                .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}: {c}"))
                .dump_options_with_quotes())
    except Exception as e:
        print(e)
        return
    return position_pie


def bar_salary() -> Bar():
    ress = partJobInfo.objects.all()
    salary_list = []
    salary_dic = {}
    for i in ress:
        if i.price and 5 <= i.price <= 200:
            if i.price in salary_dic:
                salary_dic[i.price] += 1
            else:
                salary_dic[i.price] = 1
    x = sorted(list(salary_dic.keys()))
    y = [salary_dic[i] for i in x]
    x = [str(i) for i in x]
    try:
        salary_bar = (
            Bar()
                .add_xaxis(x)
                .add_yaxis("元/小时", y, color=Faker.rand_color())
                .set_global_opts(
                title_opts=opts.TitleOpts(title="数量"),
                datazoom_opts=[opts.DataZoomOpts(), opts.DataZoomOpts(type_="inside")],
            )
                .dump_options_with_quotes()
        )
    except Exception as e:
        print(e)
        return
    return salary_bar


def education_Pie() -> Pie():
    ress = partJobInfo.objects.all()
    education_dic = {}
    for i in ress:
        if i.education in education_dic:
            education_dic[i.education] += 1
        else:
            education_dic[i.education] = 1
    c = (
        Pie()
            .add(
            "",

            list(education_dic.items())
            ,
            center=["40%", "50%"],
        )
            .set_global_opts(
            title_opts=opts.TitleOpts(title="学历验饼图"),
            legend_opts=opts.LegendOpts(type_="scroll", pos_left="80%", orient="vertical"),
        )
            .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}: {c}"))
            .dump_options_with_quotes()
    )
    return c


# from pyecharts.datasets import register_url
from app01.models import City
from pyecharts.charts import Map


def district_Geo() -> Map():
    ress = City.objects.filter()
    city_dic = {}
    for i in ress:
        city_dic[i.name] = i.JobCount
    # print(city_dic)
    c = (
        Map()
            .add(

            "",
            [list(z) for z in zip(city_dic.keys(), city_dic.values())],
            "china-cities",

            label_opts=opts.LabelOpts(is_show=False),

        )
            .set_global_opts(
            title_opts=opts.TitleOpts(title="城市热力图"),
            visualmap_opts=opts.VisualMapOpts(min_=0, max_=max(city_dic.values())),

        )
            .dump_options_with_quotes()
    )

    return c


def district_Line() -> Line():
    ress = partJobInfo.objects.filter()
    dateTime_dic = {}
    for i in ress:
        if i.dateTime.year in dateTime_dic:
            dateTime_dic[i.dateTime.year] += 1
        else:
            dateTime_dic[i.dateTime.year] = +1
    x_data = [i for i in dateTime_dic.keys()]
    y_data = [dateTime_dic[i] for i in x_data]
    x_data = sorted(x_data)
    x_data = [str(i) for i in x_data]
    print(x_data)
    print(y_data)
    c = (
        Line()
            .set_global_opts(
            tooltip_opts=opts.TooltipOpts(is_show=False),
            xaxis_opts=opts.AxisOpts(type_="category"),
            yaxis_opts=opts.AxisOpts(
                type_="value",
                axistick_opts=opts.AxisTickOpts(is_show=True),
                splitline_opts=opts.SplitLineOpts(is_show=True),
            ),
        )
            .add_xaxis(xaxis_data=x_data)
            .add_yaxis(
            series_name="",
            y_axis=y_data,
            symbol="emptyCircle",
            is_symbol_show=True,
            is_smooth=True,
            label_opts=opts.LabelOpts(is_show=False),
        )
            .dump_options_with_quotes()
    )

    return c


from app01 import utils
import os

base_dir = os.path.dirname(os.path.abspath(__file__))


def word_cloud() -> WordCloud():
    json_path = os.path.join(base_dir, "wordCloud.json")
    with open(json_path, "r", encoding="utf8") as f:
        word = json.load(f)
    c = (
        WordCloud()
            .add(
            "",
            word,
            word_size_range=[20, 100],
            textstyle_opts=opts.TextStyleOpts(font_family="cursive"),
        )
            .set_global_opts(title_opts=opts.TitleOpts(title="WordCloud"))
            .dump_options_with_quotes()
    )
    return c


class PositionNameView(APIView):
    def get(self, request, *args, **kwargs):
        start = request.GET.get('start', 100)
        end = request.GET.get('end', 150)
        print(start)
        print(end)
        return JsonResponse(json.loads(pie_position(int(start), int(end))))


class SalaryView(APIView):
    def get(self, request, *args, **kwargs):
        return JsonResponse(json.loads(bar_salary()))


class EducationView(APIView):
    def get(self, request, *args, **kwargs):
        return JsonResponse(json.loads(education_Pie()))


class WordCloudView(APIView):
    def get(self, request, *args, **kwargs):
        return JsonResponse(json.loads(word_cloud()))


class DistrictView(APIView):
    def get(self, request, *args, **kwargs):
         return JsonResponse(json.loads(district_Geo()))
        #return JsonResponse(json.loads(district_Line()))

class DistrictLineView(APIView):
    def get(self, request, *args, **kwargs):
        #return JsonResponse(json.loads(district_Geo()))#本来是地图现在换成时间曲线
        return JsonResponse(json.loads(district_Line()))


@login_required
def District(request):
    context = {
        'current_user': {'user': request.user, 'is_login': request.user.is_authenticated},
        'IsSuccess': 'district'
    }
    return render(request, 'districtT.html', context=context)

@login_required
def DistrictLine(request):
    context = {
        'current_user': {'user': request.user, 'is_login': request.user.is_authenticated},
        'IsSuccess': 'districtLine'
    }
    return render(request, 'districtLine.html', context=context)


@login_required
def WordCloudT(request):
    context = {
        'IsSuccess': 'wordCloud',
        'current_user': {'user': request.user, 'is_login': request.user.is_authenticated},
    }
    return render(request, 'worldCloudT.html', context=context)


@login_required
def Salary(request):
    context = {
        'current_user': {'user': request.user, 'is_login': request.user.is_authenticated},
        'IsSuccess': 'salary'
    }
    return render(request, 'salaryT.html', context=context)


@login_required
def Index(request):
    context = {
        'current_user': {'user': request.user, 'is_login': request.user.is_authenticated},
        'IsSuccess': 'workType'
    }
    return render(request, 'indexT.html', context=context)


@login_required
def Education(request):
    context = {
        'current_user': {'user': request.user, 'is_login': request.user.is_authenticated},
        'IsSuccess': 'education'
    }
    return render(request, 'educationT.html', context=context)


@login_required
def my_page(request):
    context = {

        'current_user': {'user': request.user, 'is_login': request.user.is_authenticated},

    }
    return render(request, 'my_page.html', context)

网站展示项目/app01/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>Awesome-pyecharts</title>
    <script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts.min.js"></script>
    <!-- 新 Bootstrap 核心 CSS 文件 -->
    <link href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block head %}

    {% endblock %}
</head>
<body>
<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <nav class="navbar navbar-default navbar-inverse" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1"><span
                            class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span
                            class="icon-bar"></span><span class="icon-bar"></span></button>
                    <a class="navbar-brand" href="#">
                        基于Scrapy的网上兼职网数据爬虫分析
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li {% if 'workType' in IsSuccess %} class="active" {% endif %}>
                            <a href="/">工作类别</a>
                        </li>
                        <li {% if 'salary' in IsSuccess %} class="active" {% endif %}>
                            <a href="/salary">时薪</a>
                        </li>

                        <li {% if  'districtLine'  in IsSuccess %} class="active" {% endif %}>
                            <a href="/districtLine">历年兼职曲线</a>
                        </li>

                        <li {% if  'district'  in IsSuccess %} class="active" {% endif %}>
                            <a href="/district">城市区域分布</a>
                        </li>

                        <li {% if 'education' in IsSuccess %} class="active" {% endif %}>
                            <a href="/education">职位学历要求</a>
                        </li>
                        <li {% if 'wordCloud' in IsSuccess %} class="active" {% endif %}>
                            <a href="/wordCloud">词云图</a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                           {% if current_user.user.is_staff %}
                        <li>

                            <a href="/admin">数据管理</a>

                        </li>
                          {% endif %}
                        <li class="dropdown">
                            {% if current_user.is_login %}
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ current_user.user }}<strong
                                    class="caret"></strong></a>
                            <ul class="dropdown-menu">

                                <li>
                                    <a href="{% url 'app01:my-page' %}">个人信息</a>
                                </li>

                                <li class="divider">
                                </li>
                                <li>
                                    <a href="{% url 'accounts:logout' %}">退出</a>
                                </li>

                            </ul>

                             {% else %}
                            <a href="{% url 'accounts:login' %}" class="dropdown-toggle" data-toggle="dropdown">点击登录</a>
                             {% endif %}
                        </li>
                    </ul>

                </div>

            </nav>
            {% block content %}

            {% endblock %}

            {% block script %}

            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

网站展示项目/app01/templates/base_form.html
{% for field in form %}
<div class="form-group">
  <label for="" class="text-dark">{{ field.label }}</label>
  <div>{{field}}</div>
  {% for error in field.errors %}
    <div class="field-error">
      {{error}}
    </div>
  {% endfor %}
  <small class="text-black-50">
    {{ field.help_text }}
  </small>
</div>
{% endfor %}

网站展示项目/app01/templates/indexT.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="row clearfix">
        <div class="col-md-2 column">
&nbsp
{#            <div class="form-group">#}
{#                <label for="exampleInputEmail1">工作类别开始</label><input type="number" class="form-control"#}
{#                                                                     id="positionNameStart" placeholder="默认100"/>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <label for="exampleInputPassword1">工作类别结束</label><input type="number" class="form-control"#}
{#                                                                        id="positionNameEnd" placeholder="默认150"/>#}
{#            </div>#}
{#            <button type="submit" class="btn btn-default" id="positionNameSubmit">Submit</button>#}

        </div>
        <div class="col-md-8 column">
            <div id="bar" style="width:1000px; height:600px;"></div>
            &nbsp;
        </div>
        <div class="col-md-2 column">
            &nbsp;
        </div>
    </div>

{% endblock %}

{% block script %}

<script>
    var chart = echarts.init(document.getElementById('bar'), 'white', {renderer: 'canvas'});

    $(
        function () {
            fetchData(chart);
        }
    );

    function fetchData() {
        $.ajax({
            type: "GET",
            url: "/demo/PositionNameView",
            dataType: 'json',
            success: function (result) {
                chart.setOption(result.data);
            }
        });
    }

    $('#positionNameSubmit').click(function () {
        $.ajax({
            url: "/demo/PositionNameView",
            type: 'get',
            data: {
                // 两种获取csrf校验值的方式


                "start": $('#positionNameStart').val(),
                "end": $('#positionNameEnd').val(),
            }, beforeSend: function () {

            },
            success: function (result) {

                if (result) {
                    // 登录成功直接跳转网址主页
                    var chart = echarts.init(document.getElementById('bar'), 'white', {renderer: 'canvas'});
                    chart.setOption(result.data);

                } else {
                    // 将错误信息统一渲染到button按钮下面的span标签中

                }
            }
        })

    })
</script>
{% endblock %}

网站展示项目/app01/templates/my_page.html

{% extends 'base.html' %}
{% load static %}





{% block content %}

<div class="card">
  <div class="card-header">
      <h3>hi, {{ current_user.user.username }}</h3>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-md-4 offset-md-1 user-image">
        {% if current_user.user.userprofile.picture %}
          <img src="{{ current_user.user.userprofile.picture.url }}" alt="用户头像" class="rounded-circle" width="200" height="200" id="user_picture_img">
        {% else %}
        <img src="{% static 'img/bs.png' %}" alt="用户头像" class="rounded-circle" width="200" height="200" id="user_picture_img">
          {% endif %}
      </div>
      <div class="col">
        <!-- https://www.qdskill.com/docs/bootstrap/docs/4.0/components/forms/
         -->
          <form action="{% url 'accounts:userprofile' %}" method="post" novalidate  enctype="multipart/form-data">
{#            {% csrf_token %}#}

              <div class="form-group row">
                  <label for="inputUser" class="col-sm-2 col-form-label">姓名</label>
                  <div class="col-sm-10">
                    <input type="text" readonly class="form-control" id="inputUser" name="username" placeholder="username" value="{{ current_user.user.username }}">
                  </div>
              </div>
              <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">邮箱</label>
                <div class="col-sm-10">
                  <input type="email" class="form-control" id="inputEmail3" name="email" placeholder="Email" value="{{ current_user.user.email }}">
                </div>
              </div>
              <div class="form-group row">
                <label for="inputPhoneNumber" class="col-sm-2 col-form-label">手机</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="inputPhoneNumber" name="phoneNumber" placeholder="13588888888" value="{{ current_user.user.userprofile.phone_number }}">
                </div>
              </div>

              <fieldset class="form-group">
                <div class="row">
                  <legend class="col-form-label col-sm-2 pt-0">性别</legend>
                  <div class="col-sm-10">
                    <div class="form-check">
                      <!-- <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="1" checked> -->
                      <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="1" 
                      {% if current_user.user.userprofile.sex == '1' %}
                      checked
                      {% endif %}
                      >
                      <label class="form-check-label" for="gridRadios1">
                        男
                      </label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="2"
                      {% if current_user.user.userprofile.sex == '2' %}
                      checked
                      {% endif %}
                      >
                      <label class="form-check-label" for="gridRadios2">
                        女
                      </label>
                    </div>
                  </div>
                </div>
              </fieldset>
              <label class="" for="user_picture">
                  选择头像(200x200)
                </label>
              <div class="form-group row">
                  <div class="col-sm-10">
                  <input type="file" name="picture" class="form-control-file" id="user_picture">
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-10">
                  <button type="submit" class="btn btn-primary">更新</button>
                </div>
              </div>
            </form>
      </div>
    </div>
  </div>
</div>


{% endblock %}
{% block js %}
<script src="{% static 'js/edit.js' %}"></script>
{% endblock %}

网站展示项目/app01/templates/salaryT.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row clearfix">
        <div class="col-md-2 column">

            &nbsp;

        </div>
        <div class="col-md-8 column">
            <div id="bar" style="width:1000px; height:600px;"></div>
            &nbsp;
        </div>
        <div class="col-md-2 column">
            &nbsp;
        </div>
    </div>

{% endblock %}


{% block script %}


<script>
    var chart = echarts.init(document.getElementById('bar'), 'white', {renderer: 'canvas'});

    $(
        function () {
            fetchData(chart);
        }
    );

    function fetchData() {
        $.ajax({
            type: "GET",
            url: "/demo/SalaryView",
            dataType: 'json',
            success: function (result) {
                chart.setOption(result.data);
            }
        });
    }


</script>
{% endblock %}