网站展示项目/JobAs/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('app01.urls')),

]





网站展示项目/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    # ex: /accounts/login/
    path('login/', views.custom_login, name="login"),
    # ex: /accounts/logout/
    path('logout/', views.custom_logout, name="logout"),
    # ex: /accounts/register/
    path('register/', views.register, name="register"),
    # ex: /accounts/userprofile/
    path('userprofile/', views.update_userprofile, name="userprofile"),
    
]

网站展示项目/accounts/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now as timezone_now


# Create your models here.
def upload_to(instance, filename):
    now = timezone_now()
    base, ext = os.path.splitext(filename)
    ext = ext.lower()
    return f"users/{now:%Y/%m/%Y%m%d%H%M%S}{ext}"


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(blank=True, null=True, max_length=11)
    picture = models.FileField(blank=True, null=True, upload_to=upload_to)
    sex = models.CharField(max_length=2, choices=(("1", '男'), ("2", '女')), default="1")
    is_law = models.BooleanField(default=False)
    law_id = models.CharField(max_length=100,default="")
    class Meta:
        verbose_name="用户信息"
        verbose_name_plural= verbose_name


    def __str__(self):
        return self.user.username

网站展示项目/accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(
        widget = forms.PasswordInput
    )
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

网站展示项目/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .models import UserProfile
from .forms import UserForm


# Create your views here.
def custom_login(request):
    if request.method == 'POST':
        # 获取数据
        username = request.POST['username']
        password = request.POST['password']
        # print(username, password)
        # 验证用户是否合法
        user = authenticate(username=username, password=password)
        if user:
            # 登录
            if user.is_active:
                login(request, user)
                # 返回页面
                return redirect(reverse('app01:index'))
            else:
                return render(request, 'accounts/login.html', {'error_message': '用户没有被激活，联系DE8UG'})
        else:
            return render(request, 'accounts/login.html', {'error_message': '用户名或密码错误！'})

    return render(request, 'accounts/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        # 如果数据合法，保存到user
        user = form.save(commit=False)
        print(form.cleaned_data)
        user.set_password(form.cleaned_data['password'])
        user.save()

        # 同步保存到profile
        profile = UserProfile()
        profile.user = user
        profile.save()

        login(request, user)
        return redirect('app01:index')

    context = {
        'form': form
    }
    return render(request, 'accounts/register.html', context)


def custom_logout(request):
    logout(request)
    return redirect('accounts:login')


@login_required
def update_userprofile(request):
    try: 
        if request.method == 'POST':
            # 获取数据
            data = request.POST
            f = request.FILES
            print(data, f)
            # 找到用户
            user = User.objects.get(username=data['username'])
            print(user)
            # 更新数据
            profile = UserProfile.objects.get(user=user)
            if profile:
                profile.email = data['email']
                profile.sex = data['gridRadios']
                profile.phone_number = data['phoneNumber']
                profile.picture = f['picture']
                profile.law_id = data['inputLawId']
                # 保存
                profile.save()
    except Exception as e:
        print(e)
    return redirect("app01:my-page")



网站展示项目/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}| 登录{% endblock %}
{% block login_active %}active{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}

<div class="container contact-form">
        <div class="contact-image">
            &nbsp;
        </div>
        <form class="form-horizontal" role="form" action="{% url 'accounts:login'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h3>登录</h3>
           <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                            <input class="form-control" placeholder="用户名" maxlength="30" name="username" type="text">
                    </div>
                    <div class="form-group">
                            <input class="form-control" placeholder="密码" maxlength="30" name="password" type="password">
                    </div>
                    <div class="form-group">
                        <input type="submit" name="btnSubmit" class="btnContact" value="提交" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        &nbsp
                    </div>
                </div>
            </div>
        </form>
        {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <div class="no-account">
                还没有账户? <a href="{% url 'accounts:register' %}">点这里</a> 注册.
        </div>
</div>

{% endblock %}


网站展示项目/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}| 注册{% endblock %}
{% block register_active %}active{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}

<div class="container contact-form">
        <div class="contact-image">
    &nbsp;
        </div>
        <form class="form-horizontal" role="form" action="{% url 'accounts:register'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h3>注册</h3>
           <div class="row">
                <div class="col-md-6">
                    <!-- {{form.as_p}} -->
                    {% include 'base_form.html' %}
                    <div class="form-group">
                        <input type="submit" name="btnSubmit" class="btnContact" value="提交" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
&nbsp;
                    </div>
                </div>
            </div>
        </form>
        {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <div class="no-account">
                已经有账户? <a href="{% url 'accounts:login' %}">点这里</a> 登录.
        </div>
</div>

{% endblock %}
